# Generated by Django 6.0.4 on 2026-04-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inn_kpp",
                    models.CharField(blank=True, max_length=32, verbose_name="ИНН/КПП"),
                ),
                (
                    "ogrn_passport",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="ОГРН/Паспорт"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("registered", "Зарегистрирован"),
                        ],
                        default="registered",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ("name",),
            },
        ),
    ]
