# Generated by Django 6.0.4 on 2026-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_organizationcontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceMan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("disabled", "Отключен"),
                            ("deleted", "Удален"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Сервисный инженер",
                "verbose_name_plural": "Сервисные инженеры",
                "ordering": ("full_name",),
            },
        ),
    ]
