# Generated by Django 6.0.4 on 2026-04-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_serviceman"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "group",
                    models.CharField(blank=True, max_length=255, verbose_name="Группа"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Категория товара",
                "verbose_name_plural": "Категории товаров",
                "ordering": ("group", "name"),
            },
        ),
    ]
