# Generated by Django 6.0.4 on 2026-04-25 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_productcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "sku",
                    models.CharField(blank=True, max_length=128, verbose_name="Артикул"),
                ),
                (
                    "weight",
                    models.CharField(blank=True, max_length=64, verbose_name="Вес"),
                ),
                (
                    "dimensions",
                    models.CharField(blank=True, max_length=128, verbose_name="Габариты"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_models",
                        to="services.brand",
                        verbose_name="Бренд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель товара",
                "verbose_name_plural": "Модели товаров",
                "ordering": ("name",),
            },
        ),
    ]
