# Generated by Django 6.0.4 on 2026-04-25 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_brands_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_models",
                to="services.productcategory",
                verbose_name="Категория товара",
            ),
        ),
    ]
