# Generated by Django 6.0.4 on 2026-04-24 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_statusdirectory_scale_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consumable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("site", models.URLField(blank=True, verbose_name="Сайт")),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Тип устройства"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Цветность"
                    ),
                ),
                (
                    "format_print",
                    models.CharField(blank=True, max_length=8, verbose_name="Формат"),
                ),
                (
                    "speed_print",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Скорость печати (стр/мин)"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Артикул"
                    ),
                ),
                (
                    "weight",
                    models.CharField(blank=True, max_length=64, verbose_name="Вес"),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Габариты"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumables",
                        to="services.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumables",
                        to="services.productcategory",
                        verbose_name="Категория товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расходный материал",
                "verbose_name_plural": "Расходные материалы",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ConsumableCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consumable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibilities",
                        to="services.consumable",
                        verbose_name="Расходный материал",
                    ),
                ),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumable_links",
                        to="services.productmodel",
                        verbose_name="Модель товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Совместимость расходного материала",
                "verbose_name_plural": "Совместимость расходных материалов",
                "ordering": ("product_model__name",),
            },
        ),
        migrations.AddField(
            model_name="consumable",
            name="compatible_models",
            field=models.ManyToManyField(
                blank=True,
                related_name="compatible_consumables",
                through="services.ConsumableCompatibility",
                to="services.productmodel",
                verbose_name="Совместимые модели товаров",
            ),
        ),
        migrations.AddConstraint(
            model_name="consumablecompatibility",
            constraint=models.UniqueConstraint(
                fields=("consumable", "product_model"),
                name="uniq_consumable_product_model",
            ),
        ),
    ]
