# Generated by Django 6.0.4 on 2026-04-25 01:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_clientequipment_repairdocument_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientequipment",
            options={
                "ordering": ("organization__name", "product_model__name", "id"),
                "verbose_name": "Техника клиента",
                "verbose_name_plural": "Техника клиентов",
            },
        ),
        migrations.AddField(
            model_name="repairdocument",
            name="client_equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repair_documents",
                to="services.clientequipment",
                verbose_name="Техника клиента",
            ),
        ),
        migrations.AddField(
            model_name="repairdocument",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_revisions",
                to="services.repairdocument",
                verbose_name="Предыдущий документ",
            ),
        ),
        migrations.AddField(
            model_name="repairdocument",
            name="status_edited_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата редактирования статуса",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clientequipment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_equipments",
                to="services.organization",
                verbose_name="Организация",
            ),
        ),
    ]
