# Generated by Django 6.0.4 on 2026-04-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_alter_clientequipment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="Индекс"),
                ),
                (
                    "locality",
                    models.CharField(max_length=255, verbose_name="Населенный пункт"),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Улица/Проспект"
                    ),
                ),
                (
                    "house",
                    models.CharField(blank=True, max_length=32, verbose_name="Дом"),
                ),
                (
                    "building",
                    models.CharField(blank=True, max_length=32, verbose_name="Корпус"),
                ),
                (
                    "structure",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Строение"
                    ),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=32, verbose_name="Этаж"),
                ),
                (
                    "room",
                    models.CharField(blank=True, max_length=64, verbose_name="Комната"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
                "ordering": ("locality", "street", "house", "id"),
            },
        ),
    ]
