# Generated by Django 6.0.4 on 2026-04-25 10:21

from django.db import migrations, models


def forwards_copy_text_address_to_directory(apps, schema_editor):
    Organization = apps.get_model("services", "Organization")
    Address = apps.get_model("services", "Address")

    for org in Organization.objects.exclude(address="").iterator():
        raw_address = (org.address or "").strip()
        if not raw_address:
            continue

        locality = raw_address[:255]
        note = raw_address if len(raw_address) > 255 else ""

        addr, _ = Address.objects.get_or_create(
            postal_code="",
            locality=locality,
            street="",
            house="",
            building="",
            structure="",
            floor="",
            room="",
            note=note,
        )
        org.addresses.add(addr)


def backwards_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0018_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="addresses",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizations",
                to="services.address",
                verbose_name="Адреса",
            ),
        ),
        migrations.RunPython(forwards_copy_text_address_to_directory, backwards_noop),
    ]
