# Generated by Django 6.0.4 on 2026-04-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0020_remove_organization_address"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE services_organization_addresses "
                        "ADD COLUMN main_office bool NOT NULL DEFAULT 0"
                    ),
                    reverse_sql=(
                        "ALTER TABLE services_organization_addresses "
                        "DROP COLUMN main_office"
                    ),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="OrganizationAddress",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "main_office",
                            models.BooleanField(default=False, verbose_name="Главный офис"),
                        ),
                        (
                            "address",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="organization_links",
                                to="services.address",
                                verbose_name="Адрес",
                            ),
                        ),
                        (
                            "organization",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="address_links",
                                to="services.organization",
                                verbose_name="Организация",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "services_organization_addresses",
                        "verbose_name": "Адрес организации",
                        "verbose_name_plural": "Адреса организаций",
                        "ordering": (
                            "-main_office",
                            "address__locality",
                            "address__street",
                            "address__house",
                            "id",
                        ),
                    },
                ),
                migrations.AlterField(
                    model_name="organization",
                    name="addresses",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="organizations",
                        through="services.OrganizationAddress",
                        through_fields=("organization", "address"),
                        to="services.address",
                        verbose_name="Адреса",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="organizationaddress",
                    constraint=models.UniqueConstraint(
                        fields=("organization", "address"),
                        name="unique_organization_address_link",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="organizationaddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("main_office", True)),
                fields=("organization",),
                name="unique_main_office_per_organization",
            ),
        ),
    ]
