# Generated by Django 6.0.4 on 2026-04-25 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0021_organizationaddress_alter_organization_addresses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inn_kpp",
                    models.CharField(blank=True, max_length=32, verbose_name="ИНН/КПП"),
                ),
                (
                    "ogrn_passport",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="ОГРН/Паспорт"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("registered", "Зарегистрирован"),
                        ],
                        default="registered",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Сервисный центр",
                "verbose_name_plural": "Сервисные центры",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ServiceCenterAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_office",
                    models.BooleanField(default=False, verbose_name="Главный офис"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_center_links",
                        to="services.address",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "service_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_links",
                        to="services.servicecenter",
                        verbose_name="Сервисный центр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес сервисного центра",
                "verbose_name_plural": "Адреса сервисных центров",
                "db_table": "services_servicecenter_addresses",
                "ordering": (
                    "-main_office",
                    "address__locality",
                    "address__street",
                    "address__house",
                    "id",
                ),
            },
        ),
        migrations.AddField(
            model_name="servicecenter",
            name="addresses",
            field=models.ManyToManyField(
                blank=True,
                related_name="service_centers",
                through="services.ServiceCenterAddress",
                through_fields=("service_center", "address"),
                to="services.address",
                verbose_name="Адреса",
            ),
        ),
        migrations.CreateModel(
            name="ServiceCenterContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Должность"
                    ),
                ),
                ("phone", models.CharField(max_length=32, verbose_name="Телефон")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="services.servicecenter",
                        verbose_name="Сервисный центр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт сервисного центра",
                "verbose_name_plural": "Контакты сервисных центров",
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="servicecenteraddress",
            constraint=models.UniqueConstraint(
                fields=("service_center", "address"),
                name="unique_service_center_address_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecenteraddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("main_office", True)),
                fields=("service_center",),
                name="unique_main_office_per_service_center",
            ),
        ),
    ]
