# Generated by Django 6.0.4 on 2026-04-25 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0024_repairdocument_service_center_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptanceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptance_documents",
                        to="services.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ приемки техники",
                "verbose_name_plural": "Документы приемки техники",
                "ordering": ("-date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AcceptanceDocumentEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acceptance_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_links",
                        to="services.acceptancedocument",
                        verbose_name="Документ приемки",
                    ),
                ),
                (
                    "client_equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptance_links",
                        to="services.clientequipment",
                        verbose_name="Техника клиента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Техника в документе приемки",
                "verbose_name_plural": "Техника в документах приемки",
                "ordering": (
                    "client_equipment__product_model__name",
                    "client_equipment__serial_number",
                    "id",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("acceptance_document", "client_equipment"),
                        name="unique_acceptance_document_equipment",
                    )
                ],
            },
        ),
    ]
