# Generated by Django 6.0.4 on 2026-04-26 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0025_acceptancedocument_acceptancedocumentequipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptancedocument",
            name="serviceman",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acceptance_documents",
                to="services.serviceman",
                verbose_name="Сервисный инженер",
            ),
        ),
    ]
