# Generated by Django 6.0.4 on 2026-04-26 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0027_acceptancedocumentequipment_repair_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_documents",
                        to="services.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "serviceman",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_documents",
                        to="services.serviceman",
                        verbose_name="Сервисный инженер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ отгрузки техники",
                "verbose_name_plural": "Документы отгрузки техники",
                "ordering": ("-date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ShipmentDocumentEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_links",
                        to="services.clientequipment",
                        verbose_name="Техника клиента",
                    ),
                ),
                (
                    "repair_document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_equipment_link",
                        to="services.repairdocument",
                        verbose_name="Документ ремонта",
                    ),
                ),
                (
                    "shipment_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_links",
                        to="services.shipmentdocument",
                        verbose_name="Документ отгрузки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Техника в документе отгрузки",
                "verbose_name_plural": "Техника в документах отгрузки",
                "ordering": (
                    "client_equipment__product_model__name",
                    "client_equipment__serial_number",
                    "id",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shipment_document", "client_equipment"),
                        name="unique_shipment_document_equipment",
                    )
                ],
            },
        ),
    ]
