# Generated by Django 6.0.4 on 2026-04-26 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0028_shipmentdocument_shipmentdocumentequipment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceExchangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("export", "Выгрузка"), ("import", "Загрузка")],
                        max_length=16,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("directories", "Справочники"),
                            ("documents", "Документы"),
                        ],
                        max_length=16,
                        verbose_name="Раздел",
                    ),
                ),
                (
                    "result_status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("error", "Ошибка")],
                        max_length=16,
                        verbose_name="Результат",
                    ),
                ),
                (
                    "dry_run",
                    models.BooleanField(default=False, verbose_name="Только проверка"),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя файла"
                    ),
                ),
                (
                    "selected_keys",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Выбранные наборы"
                    ),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="Сводка"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_exchange_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог обмена данными",
                "verbose_name_plural": "Логи обмена данными",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
