# Generated by Django 6.0.4 on 2026-04-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0029_serviceexchangelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceexchangelog",
            name="action",
            field=models.CharField(
                choices=[
                    ("export", "Выгрузка"),
                    ("import", "Загрузка"),
                    ("cleanup", "Очистка"),
                ],
                max_length=16,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="serviceexchangelog",
            name="section",
            field=models.CharField(
                choices=[
                    ("directories", "Справочники"),
                    ("documents", "Документы"),
                    ("all", "Все"),
                ],
                max_length=16,
                verbose_name="Раздел",
            ),
        ),
    ]
