# Generated by Django 6.0.4 on 2026-04-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0030_alter_serviceexchangelog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceexchangelog",
            name="action",
            field=models.CharField(
                choices=[
                    ("export", "Выгрузка"),
                    ("import", "Загрузка"),
                    ("cleanup", "Очистка"),
                    ("archive", "Архив базы"),
                ],
                max_length=16,
                verbose_name="Действие",
            ),
        ),
    ]
