# Generated by Django 6.0.4 on 2026-04-26 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0031_alter_serviceexchangelog_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Цена за единицу",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Работа",
                "verbose_name_plural": "Работы",
                "ordering": ("code", "name"),
            },
        ),
        migrations.CreateModel(
            name="WorkDirectoryConsumable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consumable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_links",
                        to="services.consumable",
                        verbose_name="Расходный материал",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumable_links",
                        to="services.workdirectory",
                        verbose_name="Работа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расходный материал в работе",
                "verbose_name_plural": "Расходные материалы в работах",
                "ordering": ("consumable__name", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("work", "consumable"), name="uniq_work_consumable"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkDirectoryPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_links",
                        to="services.part",
                        verbose_name="Запчасть",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_links",
                        to="services.workdirectory",
                        verbose_name="Работа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запчасть в работе",
                "verbose_name_plural": "Запчасти в работах",
                "ordering": ("part__name", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("work", "part"), name="uniq_work_part"
                    )
                ],
            },
        ),
    ]
