# Generated by Django 6.0.4 on 2026-04-26 01:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0032_workdirectory_workdirectoryconsumable_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workdirectory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="uniq_workdirectory_code_ci",
            ),
        ),
    ]
