# Generated by Django 6.0.4 on 2026-04-26 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0034_repairdocumentconsumable_manual_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentCharacteristicType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="Код"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Тип характеристики техники",
                "verbose_name_plural": "Типы характеристик техники",
                "ordering": ("sort_order", "name", "id"),
            },
        ),
        migrations.AlterModelOptions(
            name="productmodel",
            options={
                "ordering": ("name",),
                "verbose_name": "Техника",
                "verbose_name_plural": "Техника",
            },
        ),
        migrations.AlterField(
            model_name="consumable",
            name="compatible_models",
            field=models.ManyToManyField(
                blank=True,
                related_name="compatible_consumables",
                through="services.ConsumableCompatibility",
                to="services.productmodel",
                verbose_name="Совместимая техника",
            ),
        ),
        migrations.AlterField(
            model_name="consumablecompatibility",
            name="product_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumable_links",
                to="services.productmodel",
                verbose_name="Техника",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="compatible_models",
            field=models.ManyToManyField(
                blank=True,
                related_name="compatible_parts",
                through="services.PartCompatibility",
                to="services.productmodel",
                verbose_name="Совместимая техника",
            ),
        ),
        migrations.AlterField(
            model_name="partcompatibility",
            name="product_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_links",
                to="services.productmodel",
                verbose_name="Техника",
            ),
        ),
        migrations.CreateModel(
            name="ProductModelCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Значение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "characteristic_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="services.equipmentcharacteristictype",
                        verbose_name="Характеристика",
                    ),
                ),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="services.productmodel",
                        verbose_name="Техника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика техники",
                "verbose_name_plural": "Характеристики техники",
                "ordering": (
                    "characteristic_type__sort_order",
                    "characteristic_type__name",
                    "id",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_model", "characteristic_type"),
                        name="uniq_model_characteristic_type",
                    )
                ],
            },
        ),
    ]
