# Generated by Django 6.0.4 on 2026-04-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0036_seed_model_characteristics"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentcharacteristictype",
            name="value_kind",
            field=models.CharField(
                choices=[
                    ("text", "Текст"),
                    ("number", "Число"),
                    ("boolean", "Логический (чекбокс)"),
                    ("tags", "Список (теги)"),
                ],
                default="text",
                max_length=16,
                verbose_name="Тип значения",
            ),
        ),
    ]
