# Generated by Django 6.0.4 on 2026-04-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_equipmentcharacteristictype_value_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В работе'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='planned', max_length=16, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_visits', to='services.organization', verbose_name='Организация')),
                ('serviceman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_visits', to='services.serviceman', verbose_name='Сервисный инженер')),
            ],
            options={
                'verbose_name': 'Плановый визит',
                'verbose_name_plural': 'Плановые визиты',
                'ordering': ('-date', '-id'),
            },
        ),
    ]
