# Generated by Django 6.0.4 on 2026-04-29 21:33

import django.core.validators
import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_remove_consumable_part_legacy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='catalog_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на каталог'),
        ),
        migrations.AddField(
            model_name='part',
            name='catalog_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на каталог'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='catalog_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на каталог'),
        ),
        migrations.CreateModel(
            name='ConsumableAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to=services.models.catalog_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf'])], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.consumable', verbose_name='Расходный материал')),
            ],
            options={
                'verbose_name': 'Вложение расходного материала',
                'verbose_name_plural': 'Вложения расходных материалов',
                'ordering': ('-uploaded_at', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to=services.models.catalog_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf'])], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Вложение запчасти',
                'verbose_name_plural': 'Вложения запчастей',
                'ordering': ('-uploaded_at', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductModelAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to=services.models.catalog_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf'])], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.productmodel', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Вложение техники',
                'verbose_name_plural': 'Вложения техники',
                'ordering': ('-uploaded_at', 'id'),
                'abstract': False,
            },
        ),
    ]
