# Generated by Django 6.0.4 on 2026-05-02 20:11

import django.core.validators
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0043_remove_product_model_legacy_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumableattachment",
            name="file",
            field=models.FileField(
                upload_to=services.models.catalog_attachment_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "bmp",
                            "pdf",
                            "txt",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                        ]
                    )
                ],
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="partattachment",
            name="file",
            field=models.FileField(
                upload_to=services.models.catalog_attachment_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "bmp",
                            "pdf",
                            "txt",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                        ]
                    )
                ],
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="productmodelattachment",
            name="file",
            field=models.FileField(
                upload_to=services.models.catalog_attachment_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "bmp",
                            "pdf",
                            "txt",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                        ]
                    )
                ],
                verbose_name="Файл",
            ),
        ),
    ]
