# Generated by Django 6.0.4 on 2026-05-02 20:17

import django.core.validators
import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0044_alter_consumableattachment_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptancedocument",
            name="catalog_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на каталог"),
        ),
        migrations.AddField(
            model_name="repairdocument",
            name="catalog_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на каталог"),
        ),
        migrations.AddField(
            model_name="shipmentdocument",
            name="catalog_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на каталог"),
        ),
        migrations.CreateModel(
            name="AcceptanceDocumentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название файла"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=services.models.catalog_attachment_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "bmp",
                                    "pdf",
                                    "txt",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "acceptance_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="services.acceptancedocument",
                        verbose_name="Документ приемки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение документа приемки",
                "verbose_name_plural": "Вложения документов приемки",
                "ordering": ("-uploaded_at", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RepairDocumentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название файла"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=services.models.catalog_attachment_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "bmp",
                                    "pdf",
                                    "txt",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "repair_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="services.repairdocument",
                        verbose_name="Документ ремонта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение документа ремонта",
                "verbose_name_plural": "Вложения документов ремонта",
                "ordering": ("-uploaded_at", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShipmentDocumentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название файла"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=services.models.catalog_attachment_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "bmp",
                                    "pdf",
                                    "txt",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "shipment_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="services.shipmentdocument",
                        verbose_name="Документ отгрузки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение документа отгрузки",
                "verbose_name_plural": "Вложения документов отгрузки",
                "ordering": ("-uploaded_at", "id"),
                "abstract": False,
            },
        ),
    ]
