# Generated by Django 6.0.4 on 2026-05-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0045_acceptancedocument_catalog_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptancedocumentattachment",
            name="original_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                verbose_name="Исходное имя файла",
            ),
        ),
        migrations.AddField(
            model_name="consumableattachment",
            name="original_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                verbose_name="Исходное имя файла",
            ),
        ),
        migrations.AddField(
            model_name="partattachment",
            name="original_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                verbose_name="Исходное имя файла",
            ),
        ),
        migrations.AddField(
            model_name="productmodelattachment",
            name="original_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                verbose_name="Исходное имя файла",
            ),
        ),
        migrations.AddField(
            model_name="repairdocumentattachment",
            name="original_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                verbose_name="Исходное имя файла",
            ),
        ),
        migrations.AddField(
            model_name="shipmentdocumentattachment",
            name="original_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                verbose_name="Исходное имя файла",
            ),
        ),
    ]
