# Generated by Django 6.0.4 on 2026-05-03

import django.core.validators
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0046_acceptancedocumentattachment_original_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientequipment",
            name="catalog_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на каталог"),
        ),
        migrations.CreateModel(
            name="ClientEquipmentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="Название файла")),
                (
                    "original_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Исходное имя файла",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=services.models.catalog_attachment_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "bmp",
                                    "pdf",
                                    "txt",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                        verbose_name="Файл",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки")),
                (
                    "client_equipment",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="attachments",
                        to="services.clientequipment",
                        verbose_name="Техника клиента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение техники клиента",
                "verbose_name_plural": "Вложения техники клиентов",
                "ordering": ("-uploaded_at", "id"),
            },
        ),
    ]
